package com.eventlottery.services;

import android.content.Context;
import android.graphics.Bitmap;
import android.graphics.BitmapFactory;
import android.net.Uri;

import java.io.ByteArrayOutputStream;
import java.io.InputStream;


public class Base64EncodeDecode {

    /**
     * Encodes the selected image URI into a Base64 string.
     * Generated by Google Gemini, Prompt: "'m trying to encode the image posters into base64 to store
     * as a string why is it erroring so much"
     * @param imageUri URI of the image to encode
     * @return String representation of the image in Base64
     */
    public static String encodeImageToBase64(Context context, Uri imageUri) {
        try {
            InputStream inputStream = context.getContentResolver().openInputStream(imageUri);
            Bitmap bitmap = BitmapFactory.decodeStream(inputStream);
            ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
            // Compress to JPEG to reduce size (Base64 strings can get very large)
            int maxSize = 800;
            int width = bitmap.getWidth();
            int height = bitmap.getHeight();
            float ratio = (float) width / (float) height;
            if (ratio > 1) {
                width = maxSize;
                height = (int) (width / ratio);
            } else {
                height = maxSize;
                width = (int) (height * ratio);
            }
            bitmap = Bitmap.createScaledBitmap(bitmap, width, height, true);
            bitmap.compress(Bitmap.CompressFormat.JPEG, 50, outputStream);
            byte[] byteArray = outputStream.toByteArray();
            return android.util.Base64.encodeToString(byteArray, android.util.Base64.DEFAULT);
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

    /**
     * Decodes a Base64 string into a Bitmap for display.
     * @param input Base64 string to decode
     * @return Bitmap representation of the image
     */
    public static Bitmap decodeBase64(String input) {
        if (input == null || input.isEmpty()) return null;
        try {
            byte[] decodedBytes = android.util.Base64.decode(input, android.util.Base64.DEFAULT);
            return BitmapFactory.decodeByteArray(decodedBytes, 0, decodedBytes.length);
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }
}
