package com.eventlottery.ui.adapters;

import android.graphics.Bitmap;
import android.util.Log;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;

import androidx.annotation.NonNull;
import androidx.recyclerview.widget.RecyclerView;

import com.bumptech.glide.Glide;
import com.eventlottery.R;
import com.eventlottery.model.Image;
import com.eventlottery.services.Base64EncodeDecode;

import java.util.ArrayList;
import java.util.List;

/**
 * Adapter for displaying a grid of images for admin review.
 * Handles both standard URLs and Base64 encoded image strings.
 * Part of the 'View' in MVC.
 */
public class ImageAdapter extends RecyclerView.Adapter<ImageAdapter.ImageViewHolder> {
    private static final String TAG = "ImageAdapter";
    private List<Image> images;
    private final OnImageClickListener listener;

    /**
     * Interface for handling image click events.
     */
    public interface OnImageClickListener {
        /**
         * Called when an image item is clicked in the list.
         * @param image The Image object associated with the clicked item.
         */
        void onImageClick(Image image);
    }

    /**
     * Constructs a new ImageAdapter with a click listener.
     * @param listener The listener that will handle image click events.
     */
    public ImageAdapter(OnImageClickListener listener) {
        this.images = new ArrayList<>();
        this.listener = listener;
    }

    /**
     * Updates the data set and refreshes the RecyclerView.
     * @param newImages The new list of images to display.
     */
    public void setImages(List<Image> newImages) {
        this.images = new ArrayList<>(newImages);
        notifyDataSetChanged();
    }

    @NonNull
    @Override
    public ImageViewHolder onCreateViewHolder(@NonNull ViewGroup parent, int viewType) {
        View view = LayoutInflater.from(parent.getContext())
                .inflate(R.layout.item_image_card, parent, false);
        return new ImageViewHolder(view);
    }

    @Override
    public void onBindViewHolder(@NonNull ImageViewHolder holder, int position) {
        Image image = images.get(position);
        holder.bind(image, listener);
    }

    @Override
    public int getItemCount() {
        return images.size();
    }

    /**
     * ViewHolder for image items.
     * Manages the lifecycle and binding of an individual image view.
     */
    static class ImageViewHolder extends RecyclerView.ViewHolder {
        private final ImageView imageView;

        /**
         * Initializes the ViewHolder with the item view.
         * @param itemView The view for a single item in the list.
         */
        public ImageViewHolder(@NonNull View itemView) {
            super(itemView);
            imageView = itemView.findViewById(R.id.ivReviewImage);
        }

        /**
         * Generated by Android Studio Gemini "Help diplay images with image url" 06/04/2026
         * Binds image data to the view and sets up click handling.
         * Decodes Base64 strings or loads URLs using Glide.
         * @param image The Image model to display.
         * @param listener The click listener to attach to the item.
         */
        public void bind(final Image image, final OnImageClickListener listener) {
            String urlOrBase64 = image.getUrl();
            
            if (urlOrBase64 == null || urlOrBase64.isEmpty()) {
                imageView.setImageResource(R.drawable.ic_launcher_foreground);
            } else if (urlOrBase64.startsWith("http") || urlOrBase64.startsWith("content://")) {
                // Normal URL or Uri
                Glide.with(itemView.getContext())
                        .load(urlOrBase64)
                        .placeholder(R.drawable.ic_launcher_foreground)
                        .error(R.drawable.ic_launcher_foreground)
                        .centerCrop()
                        .into(imageView);
            } else {
                // Assume Base64 string
                try {
                    Bitmap bitmap = Base64EncodeDecode.decodeBase64(urlOrBase64);
                    if (bitmap != null) {
                        Glide.with(itemView.getContext())
                                .load(bitmap)
                                .placeholder(R.drawable.ic_launcher_foreground)
                                .error(R.drawable.ic_launcher_foreground)
                                .centerCrop()
                                .into(imageView);
                    } else {
                        Log.w(TAG, "Failed to decode Base64 image for event: " + image.getEventId());
                        imageView.setImageResource(R.drawable.ic_launcher_foreground);
                    }
                } catch (Exception e) {
                    Log.e(TAG, "Error loading Base64 image", e);
                    imageView.setImageResource(R.drawable.ic_launcher_foreground);
                }
            }

            itemView.setOnClickListener(v -> {
                if (listener != null) {
                    listener.onImageClick(image);
                }
            });
        }
    }
}
